package entidades;
// Generated Jun 6, 2020 2:48:40 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ciudades generated by hbm2java
 */
public class Ciudades  implements java.io.Serializable {


     private int idCiudad;
     private Integer id;
     private String ciudad;
     private Integer codigo;
     private Set climases = new HashSet(0);
     private Set coordenadases = new HashSet(0);

    public Ciudades() {
    }

	
    public Ciudades(int idCiudad) {
        this.idCiudad = idCiudad;
    }
    public Ciudades(int idCiudad, Integer id, String ciudad, Integer codigo, Set climases, Set coordenadases) {
       this.idCiudad = idCiudad;
       this.id = id;
       this.ciudad = ciudad;
       this.codigo = codigo;
       this.climases = climases;
       this.coordenadases = coordenadases;
    }
   
    public int getIdCiudad() {
        return this.idCiudad;
    }
    
    public void setIdCiudad(int idCiudad) {
        this.idCiudad = idCiudad;
    }
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public Set getClimases() {
        return this.climases;
    }
    
    public void setClimases(Set climases) {
        this.climases = climases;
    }
    public Set getCoordenadases() {
        return this.coordenadases;
    }
    
    public void setCoordenadases(Set coordenadases) {
        this.coordenadases = coordenadases;
    }




}


