package entidades;
// Generated Jun 6, 2020 2:48:40 PM by Hibernate Tools 4.3.1



/**
 * Climas generated by hbm2java
 */
public class Climas  implements java.io.Serializable {


     private int idClima;
     private Ciudades ciudades;
     private Integer id;
     private String estado;
     private String descripcion;
     private String icon;

    public Climas() {
    }

	
    public Climas(int idClima) {
        this.idClima = idClima;
    }
    public Climas(int idClima, Ciudades ciudades, Integer id, String estado, String descripcion, String icon) {
       this.idClima = idClima;
       this.ciudades = ciudades;
       this.id = id;
       this.estado = estado;
       this.descripcion = descripcion;
       this.icon = icon;
    }
   
    public int getIdClima() {
        return this.idClima;
    }
    
    public void setIdClima(int idClima) {
        this.idClima = idClima;
    }
    public Ciudades getCiudades() {
        return this.ciudades;
    }
    
    public void setCiudades(Ciudades ciudades) {
        this.ciudades = ciudades;
    }
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getIcon() {
        return this.icon;
    }
    
    public void setIcon(String icon) {
        this.icon = icon;
    }




}


